---
apiVersion: v1
kind: Namespace
metadata:
  name: vpn-inference
  labels:
    app: vpn-inference
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vpn-inference-sa
  namespace: vpn-inference
